kind: Deployment
apiVersion: apps/v1
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 4
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller-pods
        image: bencuk/rayscale-controller:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 9000

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: tracer-node-0
  labels:
    app: tracer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
      - name: tracer-pods
        image: bencuk/rayscale-tracer:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
        env:     
        - name: CONTROLLER_ENDPOINT
          value: http://controller-api:9000/api
        - name: USE_IPADDRESS
          value: "true"
      nodeSelector:
        node: "0"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: tracer-node-1
  labels:
    app: tracer
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
      - name: tracer-pods
        image: bencuk/rayscale-tracer:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
        env:     
        - name: CONTROLLER_ENDPOINT
          value: http://controller-api:9000/api
        - name: USE_IPADDRESS
          value: "true"
      nodeSelector:
        node: "1"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: tracer-node-2
  labels:
    app: tracer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
      - name: tracer-pods
        image: bencuk/rayscale-tracer:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
        env:     
        - name: CONTROLLER_ENDPOINT
          value: http://controller-api:9000/api
        - name: USE_IPADDRESS
          value: "true"
      nodeSelector:
        node: "2"

---

kind: Service
apiVersion: v1
metadata:
  name: controller-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: controller

---

kind: Service
apiVersion: v1
metadata:
  name: controller-ui
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    app: controller