remote_theme: benc-uk/theme-msdark
title: RayScale - Ray Tracer
buttons:
  - text: Gallery
    href: http://rayscale.benco.io/examples/renders/
header-colours: 
  right: "#e5c422"
  left: "#96330f"
favicon: https://github.com/benc-uk/rayscale/raw/master/controller/webui/favicon.png
