name: Release Images

on:
  release:
    types: [published]

env:
  DOCKER_USER: bencuk
  DOCKER_REG: docker.io
  # Release semver tagged version
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  releaseImages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the tracer image
        run: docker build . -f tracer/Dockerfile --tag ghcr.io/$GITHUB_ACTOR/rayscale/tracer:$IMAGE_TAG

      - name: Build the controller image
        run: docker build . -f controller/Dockerfile --tag ghcr.io/$GITHUB_ACTOR/rayscale/controller:$IMAGE_TAG

      - name: Push to dev tag Github registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/$GITHUB_ACTOR/rayscale/tracer:$IMAGE_TAG
          docker push ghcr.io/$GITHUB_ACTOR/rayscale/controller:$IMAGE_TAG
